# Generated by Django 3.1.3 on 2020-11-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateField()),
                ('post_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShelfApp.book')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShelfApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateField()),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShelfApp.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShelfApp.user')),
            ],
        ),
    ]
